import "dotenv/config";
import mongoose from "mongoose";
import bcrypt from "bcryptjs";

import User from "./model/user.model.js";
import Car from "./model/car.model.js";
import Location from "./model/location.model.js";
import Booking from "./model/booking.model.js";
import Review from "./model/review.model.js";
import Coupon from "./model/coupon.model.js";

await mongoose.connect(process.env.MONGO_URL);
console.log("Connected to MongoDB:", process.env.MONGO_URL);

// ─── Wipe ─────────────────────────────────────────────────────────────────────
await Promise.all([
  User.deleteMany(),
  Car.deleteMany(),
  Location.deleteMany(),
  Booking.deleteMany(),
  Review.deleteMany(),
  Coupon.deleteMany(),
]);
console.log("Cleared existing data");

// ─── Locations ────────────────────────────────────────────────────────────────
const locations = await Location.insertMany([
  {
    name: "Mumbai Central Hub",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    address: "Station Road, Mumbai Central, Mumbai",
    zipCode: "400008",
    phone: "+91-22-1234-5678",
    email: "mumbai@driveease.com",
    operatingHours: { open: "06:00", close: "23:00", is24Hours: false },
    isPickupAvailable: true,
    isDropAvailable: true,
    airportLocation: false,
  },
  {
    name: "Mumbai Airport",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    address: "Terminal 2, CSIA, Andheri East, Mumbai",
    zipCode: "400099",
    phone: "+91-22-6651-0000",
    email: "airport@driveease.com",
    operatingHours: { is24Hours: true },
    isPickupAvailable: true,
    isDropAvailable: true,
    airportLocation: true,
  },
  {
    name: "Delhi Connaught Place",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    address: "Block A, Connaught Place, New Delhi",
    zipCode: "110001",
    phone: "+91-11-2345-6789",
    email: "delhi@driveease.com",
    operatingHours: { open: "07:00", close: "22:00", is24Hours: false },
    isPickupAvailable: true,
    isDropAvailable: true,
    airportLocation: false,
  },
  {
    name: "Bangalore Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    address: "80 Feet Road, Koramangala, Bangalore",
    zipCode: "560034",
    phone: "+91-80-3456-7890",
    email: "bangalore@driveease.com",
    operatingHours: { open: "08:00", close: "22:00", is24Hours: false },
    isPickupAvailable: true,
    isDropAvailable: true,
    airportLocation: false,
  },
  {
    name: "Pune Kothrud",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    address: "Karve Road, Kothrud, Pune",
    zipCode: "411038",
    phone: "+91-20-4567-8901",
    email: "pune@driveease.com",
    operatingHours: { open: "08:00", close: "21:00", is24Hours: false },
    isPickupAvailable: true,
    isDropAvailable: false,
  },
]);
console.log(`Created ${locations.length} locations`);

const [mumbaiHub, mumbaiAirport, delhi, bangalore, pune] = locations;

// ─── Users ────────────────────────────────────────────────────────────────────
const hash = (pw) => bcrypt.hash(pw, 12);
const bookingNum = () => {
  const ts = Date.now().toString(36).toUpperCase();
  const rand = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `DR${ts}${rand}`;
};

const [admin, user1, user2, user3] = await User.insertMany([
  {
    name: "Admin User",
    email: "admin@driveease.com",
    password: await hash("admin123"),
    phone: "+91-9000000001",
    role: "admin",
    isVerified: true,
    isActive: true,
  },
  {
    name: "Rahul Sharma",
    email: "rahul@example.com",
    password: await hash("password123"),
    phone: "+91-9876543210",
    role: "user",
    isVerified: true,
    isActive: true,
  },
  {
    name: "Priya Mehta",
    email: "priya@example.com",
    password: await hash("password123"),
    phone: "+91-9876543211",
    role: "user",
    isVerified: true,
    isActive: true,
  },
  {
    name: "Arjun Patel",
    email: "arjun@example.com",
    password: await hash("password123"),
    phone: "+91-9876543212",
    role: "user",
    isVerified: true,
    isActive: true,
  },
]);
console.log(`Created ${4} users (1 admin + 3 regular)`);

// ─── Cars ─────────────────────────────────────────────────────────────────────
const cars = await Car.insertMany([
  // Mumbai Hub cars
  {
    name: "Honda City ZX",
    brand: "Honda",
    model: "City ZX",
    year: 2023,
    type: "sedan",
    transmission: "automatic",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Pearl White",
    licensePlate: "MH-01-AB-1001",
    pricePerDay: 2500,
    securityDeposit: 5000,
    location: mumbaiHub._id,
    isAvailable: true,
    isFeatured: true,
    features: ["AC", "Bluetooth", "Reverse Camera", "Cruise Control"],
    description: "Comfortable sedan perfect for city drives and highway trips.",
    images: [{ url: "/cars/honda-city.jpg", isPrimary: true }],
    rating: 4.5,
    reviewCount: 2,
    specifications: { engine: "1.5L i-VTEC", power: "121 bhp", fuelEfficiency: "17.8 km/l" },
  },
  {
    name: "Hyundai Creta SX",
    brand: "Hyundai",
    model: "Creta SX",
    year: 2023,
    type: "suv",
    transmission: "automatic",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Typhoon Silver",
    licensePlate: "MH-01-AB-1002",
    pricePerDay: 3200,
    securityDeposit: 7000,
    location: mumbaiHub._id,
    isAvailable: true,
    isFeatured: true,
    features: ["AC", "Sunroof", "Bluetooth", "6 Airbags", "Ventilated Seats"],
    description: "India's most popular SUV with premium features and road presence.",
    images: [{ url: "/cars/hyundai-creta.jpg", isPrimary: true }],
    rating: 5.0,
    reviewCount: 1,
    specifications: { engine: "1.5L Turbo", power: "160 bhp", fuelEfficiency: "16.8 km/l" },
  },
  {
    name: "Maruti Swift VXi",
    brand: "Maruti",
    model: "Swift VXi",
    year: 2023,
    type: "hatchback",
    transmission: "manual",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Magma Grey",
    licensePlate: "MH-01-AB-1003",
    pricePerDay: 1400,
    securityDeposit: 3000,
    location: mumbaiHub._id,
    isAvailable: true,
    isFeatured: false,
    features: ["AC", "Bluetooth", "Power Steering"],
    description: "Nimble hatchback ideal for city commutes and tight parking.",
    images: [{ url: "/cars/maruti-swift.jpg", isPrimary: true }],
    rating: 4.0,
    reviewCount: 1,
    specifications: { engine: "1.2L DualJet", power: "90 bhp", fuelEfficiency: "23.2 km/l" },
  },
  // Mumbai Airport cars
  {
    name: "Toyota Innova Crysta",
    brand: "Toyota",
    model: "Innova Crysta",
    year: 2022,
    type: "van",
    transmission: "automatic",
    fuelType: "diesel",
    seats: 7,
    doors: 4,
    color: "Super White",
    licensePlate: "MH-04-CD-2001",
    pricePerDay: 4500,
    securityDeposit: 10000,
    location: mumbaiAirport._id,
    isAvailable: true,
    isFeatured: true,
    features: ["AC", "7 Seats", "Leather Seats", "Rear AC", "Luggage Space"],
    description: "Premium MPV perfect for airport transfers and family trips.",
    images: [{ url: "/cars/toyota-innova.jpg", isPrimary: true }],
    rating: 5.0,
    reviewCount: 1,
    specifications: { engine: "2.4L GD Diesel", power: "150 bhp", fuelEfficiency: "11.4 km/l" },
  },
  {
    name: "BMW 3 Series",
    brand: "BMW",
    model: "3 Series 320d",
    year: 2023,
    type: "luxury",
    transmission: "automatic",
    fuelType: "diesel",
    seats: 5,
    doors: 4,
    color: "Alpine White",
    licensePlate: "MH-04-CD-2002",
    pricePerDay: 9500,
    securityDeposit: 25000,
    location: mumbaiAirport._id,
    isAvailable: true,
    isFeatured: true,
    features: [
      "AC",
      "Sunroof",
      "Leather Seats",
      "Harman Kardon Sound",
      "Heads-Up Display",
      "Parking Assist",
    ],
    description: "The ultimate driving machine. Luxury meets performance.",
    images: [{ url: "/cars/bmw-3series.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "2.0L TwinPower Turbo", power: "190 bhp", topSpeed: "235 km/h" },
  },
  // Delhi cars
  {
    name: "Tata Nexon EV",
    brand: "Tata",
    model: "Nexon EV Max",
    year: 2023,
    type: "electric",
    transmission: "automatic",
    fuelType: "electric",
    seats: 5,
    doors: 4,
    color: "Fearless Red",
    licensePlate: "DL-01-EF-3001",
    pricePerDay: 3000,
    securityDeposit: 8000,
    location: delhi._id,
    isAvailable: true,
    isFeatured: true,
    features: ["AC", "Fast Charging", "Sunroof", "Connected Car Tech", "7-inch Touchscreen"],
    description: "Zero-emission SUV with 437 km range. Drive green in the capital.",
    images: [{ url: "/cars/tata-nexon-ev.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "Electric Motor", power: "143 bhp", fuelEfficiency: "17.2 km/kWh" },
  },
  {
    name: "Kia Seltos HTX",
    brand: "Kia",
    model: "Seltos HTX",
    year: 2023,
    type: "suv",
    transmission: "automatic",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Glacier White Pearl",
    licensePlate: "DL-01-EF-3002",
    pricePerDay: 3500,
    securityDeposit: 7500,
    location: delhi._id,
    isAvailable: true,
    isFeatured: false,
    features: ["AC", "Sunroof", "BOSE Sound System", "360 Camera", "ADAS"],
    description: "Feature-loaded SUV with top-of-the-line ADAS safety tech.",
    images: [{ url: "/cars/kia-seltos.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "1.5L T-GDi Turbo", power: "160 bhp", fuelEfficiency: "16.5 km/l" },
  },
  {
    name: "Mahindra Thar 4x4",
    brand: "Mahindra",
    model: "Thar LX 4x4",
    year: 2023,
    type: "suv",
    transmission: "manual",
    fuelType: "diesel",
    seats: 4,
    doors: 2,
    color: "Blazing Bronze",
    licensePlate: "DL-02-GH-3003",
    pricePerDay: 4000,
    securityDeposit: 10000,
    location: delhi._id,
    isAvailable: true,
    isFeatured: false,
    features: ["4x4 Drive", "Convertible Top", "Off-Road Tyres", "Rock Crawl Mode"],
    description: "Legendary off-roader for those who dare to go beyond roads.",
    images: [{ url: "/cars/mahindra-thar.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "2.2L mHawk Diesel", power: "132 bhp", fuelEfficiency: "15.2 km/l" },
  },
  // Bangalore cars
  {
    name: "Volkswagen Virtus",
    brand: "Volkswagen",
    model: "Virtus GT Plus",
    year: 2023,
    type: "sedan",
    transmission: "automatic",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Reflex Silver",
    licensePlate: "KA-01-IJ-4001",
    pricePerDay: 2800,
    securityDeposit: 6000,
    location: bangalore._id,
    isAvailable: true,
    isFeatured: false,
    features: ["AC", "10-inch Touchscreen", "Wireless Charging", "Sunroof", "6 Airbags"],
    description: "European engineering meets Indian roads. A sporty, refined sedan.",
    images: [{ url: "/cars/vw-virtus.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "1.5L TSI EVO", power: "150 bhp", fuelEfficiency: "17.7 km/l" },
  },
  {
    name: "MG Hector Plus",
    brand: "MG",
    model: "Hector Plus Sharp",
    year: 2022,
    type: "suv",
    transmission: "manual",
    fuelType: "hybrid",
    seats: 7,
    doors: 4,
    color: "Starry Black",
    licensePlate: "KA-01-IJ-4002",
    pricePerDay: 4200,
    securityDeposit: 9000,
    location: bangalore._id,
    isAvailable: true,
    isFeatured: false,
    features: ["AC", "14-inch i-SMART Screen", "Panoramic Sunroof", "7 Seats", "Wi-Fi Hotspot"],
    description: "Smart connected SUV with India's biggest infotainment screen.",
    images: [{ url: "/cars/mg-hector.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: {
      engine: "2.0L Turbo + 48V Mild Hybrid",
      power: "143 bhp",
      fuelEfficiency: "13.9 km/l",
    },
  },
  // Pune cars
  {
    name: "Skoda Slavia Style",
    brand: "Skoda",
    model: "Slavia Style",
    year: 2023,
    type: "sedan",
    transmission: "automatic",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Candy White",
    licensePlate: "MH-12-KL-5001",
    pricePerDay: 2600,
    securityDeposit: 5500,
    location: pune._id,
    isAvailable: true,
    isFeatured: false,
    features: ["AC", "10.1-inch Touchscreen", "Ventilated Front Seats", "Digital Cockpit"],
    description: "Czech-engineered precision. Classy, comfortable and fun to drive.",
    images: [{ url: "/cars/skoda-slavia.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "1.5L TSI", power: "150 bhp", fuelEfficiency: "18.7 km/l" },
  },
  {
    name: "Renault Duster RXZ",
    brand: "Renault",
    model: "Duster RXZ",
    year: 2022,
    type: "suv",
    transmission: "manual",
    fuelType: "diesel",
    seats: 5,
    doors: 4,
    color: "Fiery Red",
    licensePlate: "MH-12-KL-5002",
    pricePerDay: 2200,
    securityDeposit: 5000,
    location: pune._id,
    isAvailable: false,
    isFeatured: false,
    features: ["AC", "Touchscreen", "Reverse Parking Sensors", "Roof Rails"],
    description: "Rugged and dependable. A true road tripper's companion.",
    images: [{ url: "/cars/renault-duster.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "1.5L dCi Diesel", power: "110 bhp", fuelEfficiency: "19.4 km/l" },
  },

  // ── Extra cars for better filter coverage ───────────────────────────────
  {
    name: "Renault Kwid RXT",
    brand: "Renault",
    model: "Kwid RXT",
    year: 2023,
    type: "hatchback",
    transmission: "manual",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Fiery Red",
    licensePlate: "MH-12-KL-5003",
    pricePerDay: 1200,
    securityDeposit: 2500,
    location: pune._id,
    isAvailable: true,
    isFeatured: false,
    features: ["AC", "Touchscreen", "Rear Parking Sensors", "Keyless Entry"],
    description: "Compact and stylish city hatchback with great fuel economy.",
    images: [{ url: "/cars/renault-kwid.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "1.0L SCe", power: "72 bhp", fuelEfficiency: "22.3 km/l" },
  },
  {
    name: "Toyota Glanza V",
    brand: "Toyota",
    model: "Glanza V",
    year: 2023,
    type: "hatchback",
    transmission: "automatic",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Sporty Red",
    licensePlate: "KA-01-IJ-4003",
    pricePerDay: 1600,
    securityDeposit: 3500,
    location: bangalore._id,
    isAvailable: true,
    isFeatured: false,
    features: ["AC", "Bluetooth", "Sunroof", "6 Airbags", "Wireless Charging"],
    description: "Premium hatchback with great safety and comfort features.",
    images: [{ url: "/cars/toyota-glanza.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "1.2L Dual VVT-i", power: "90 bhp", fuelEfficiency: "22.4 km/l" },
  },
  {
    name: "Honda Jazz V CVT",
    brand: "Honda",
    model: "Jazz V CVT",
    year: 2022,
    type: "hatchback",
    transmission: "automatic",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Lunar Silver",
    licensePlate: "MH-01-AB-1004",
    pricePerDay: 1800,
    securityDeposit: 4000,
    location: mumbaiHub._id,
    isAvailable: true,
    isFeatured: false,
    features: ["AC", "Bluetooth", "Magic Seats", "Cruise Control", "Lane Watch Camera"],
    description: "Spacious and versatile hatchback with Honda's famous Magic Seats.",
    images: [{ url: "/cars/honda-jazz.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "1.2L i-VTEC", power: "90 bhp", fuelEfficiency: "18.7 km/l" },
  },
  {
    name: "Mercedes-Benz C-Class",
    brand: "Mercedes",
    model: "C-Class C220d",
    year: 2023,
    type: "luxury",
    transmission: "automatic",
    fuelType: "diesel",
    seats: 5,
    doors: 4,
    color: "Obsidian Black",
    licensePlate: "MH-04-CD-2003",
    pricePerDay: 11000,
    securityDeposit: 30000,
    location: mumbaiAirport._id,
    isAvailable: true,
    isFeatured: true,
    features: [
      "AC",
      "Panoramic Sunroof",
      "Burmester Sound",
      "MBUX Infotainment",
      "Heated Seats",
      "360 Camera",
    ],
    description: "The pinnacle of luxury motoring with unmatched comfort and style.",
    images: [{ url: "/cars/mercedes-c-class.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "2.0L diesel", power: "194 bhp", topSpeed: "250 km/h" },
  },
  {
    name: "Hyundai i20 Asta",
    brand: "Hyundai",
    model: "i20 Asta",
    year: 2023,
    type: "hatchback",
    transmission: "automatic",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Typhoon Silver",
    licensePlate: "DL-01-EF-3003",
    pricePerDay: 1700,
    securityDeposit: 3500,
    location: delhi._id,
    isAvailable: true,
    isFeatured: false,
    features: ["AC", "Sunroof", "Bose Sound", "Wireless Charging", "8 Airbags"],
    description: "Feature-packed premium hatchback with class-leading safety.",
    images: [{ url: "/cars/hyundai-i20.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "1.0L Turbo GDi", power: "120 bhp", fuelEfficiency: "20.6 km/l" },
  },
  {
    name: "Tata Altroz XZ+",
    brand: "Tata",
    model: "Altroz XZ+",
    year: 2023,
    type: "hatchback",
    transmission: "manual",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Avenue White",
    licensePlate: "DL-02-GH-3004",
    pricePerDay: 1500,
    securityDeposit: 3000,
    location: delhi._id,
    isAvailable: true,
    isFeatured: false,
    features: [
      "AC",
      "10.25-inch Touchscreen",
      "Connected Car Tech",
      "6 Airbags",
      "Wireless Charging",
    ],
    description: "India's safest hatchback with 5-star Global NCAP rating.",
    images: [{ url: "/cars/tata-altroz.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "1.2L Revotron", power: "86 bhp", fuelEfficiency: "19.0 km/l" },
  },

  // ── Electric type cars (Tata EVs) ──────────────────────────────────────────
  {
    name: "Tata Tigor EV",
    brand: "Tata",
    model: "Tigor EV XZ+",
    year: 2023,
    type: "electric",
    transmission: "automatic",
    fuelType: "electric",
    seats: 5,
    doors: 4,
    color: "Daytona Grey",
    licensePlate: "MH-04-CD-2004",
    pricePerDay: 2200,
    securityDeposit: 5000,
    location: mumbaiAirport._id,
    isAvailable: true,
    isFeatured: false,
    features: ["AC", "Fast Charging", "Touchscreen", "Connected Car Tech", "Auto Headlamps"],
    description: "Compact electric sedan with 306 km range. Eco-friendly city commuting made easy.",
    images: [{ url: "/cars/tata-tigor-ev.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "Electric Motor", power: "75 bhp", fuelEfficiency: "16.6 km/kWh" },
  },
  {
    name: "Tata Punch EV",
    brand: "Tata",
    model: "Punch EV Creative+",
    year: 2024,
    type: "electric",
    transmission: "automatic",
    fuelType: "electric",
    seats: 5,
    doors: 4,
    color: "Pristine White",
    licensePlate: "DL-01-EF-3004",
    pricePerDay: 2600,
    securityDeposit: 6000,
    location: delhi._id,
    isAvailable: true,
    isFeatured: true,
    features: ["AC", "Fast Charging", "Sunroof", "360 Camera", "Wireless Charging", "ADAS"],
    description:
      "Stylish micro-SUV EV with 421 km range. The most affordable long-range EV in India.",
    images: [{ url: "/cars/tata-punch-ev.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "Electric Motor", power: "122 bhp", fuelEfficiency: "18.1 km/kWh" },
  },

  // ── Luxury type (3rd car) ───────────────────────────────────────────────────
  {
    name: "Audi A4",
    brand: "Audi",
    model: "A4 Premium Plus",
    year: 2023,
    type: "luxury",
    transmission: "automatic",
    fuelType: "petrol",
    seats: 5,
    doors: 4,
    color: "Glacier White",
    licensePlate: "MH-01-AB-1005",
    pricePerDay: 10000,
    securityDeposit: 28000,
    location: mumbaiHub._id,
    isAvailable: true,
    isFeatured: true,
    features: [
      "AC",
      "Panoramic Sunroof",
      "Bang & Olufsen Sound",
      "Virtual Cockpit",
      "Heated Seats",
      "360 Camera",
    ],
    description:
      "German engineering at its finest. A perfectly balanced luxury sedan for every occasion.",
    images: [{ url: "/cars/audi-a4.jpg", isPrimary: true }],
    rating: 0,
    reviewCount: 0,
    specifications: { engine: "2.0L TFSI", power: "190 bhp", topSpeed: "240 km/h" },
  },
]);
console.log(`Created ${cars.length} cars`);

const [hondaCity, creta, swift, innova, bmw, nexonEV, , thar] = cars;

// ─── Bookings ─────────────────────────────────────────────────────────────────
const today = new Date();
const d = (offset) => new Date(today.getTime() + offset * 86400000);

const bookings = await Booking.insertMany([
  // Completed booking — Rahul booked the Creta
  {
    bookingNumber: bookingNum(),
    user: user1._id,
    car: creta._id,
    pickupLocation: mumbaiHub._id,
    dropLocation: mumbaiHub._id,
    pickupDate: d(-10),
    dropDate: d(-7),
    totalDays: 3,
    pricePerDay: creta.pricePerDay,
    baseAmount: creta.pricePerDay * 3,
    taxAmount: Math.round(creta.pricePerDay * 3 * 0.18),
    totalAmount: Math.round(creta.pricePerDay * 3 * 1.18),
    securityDeposit: creta.securityDeposit,
    status: "completed",
    paymentStatus: "paid",
    paymentMethod: "card",
    isReviewed: true,
  },
  // Completed booking — Priya booked Honda City
  {
    bookingNumber: bookingNum(),
    user: user2._id,
    car: hondaCity._id,
    pickupLocation: mumbaiHub._id,
    dropLocation: mumbaiAirport._id,
    pickupDate: d(-5),
    dropDate: d(-3),
    totalDays: 2,
    pricePerDay: hondaCity.pricePerDay,
    baseAmount: hondaCity.pricePerDay * 2,
    taxAmount: Math.round(hondaCity.pricePerDay * 2 * 0.18),
    totalAmount: Math.round(hondaCity.pricePerDay * 2 * 1.18),
    securityDeposit: hondaCity.securityDeposit,
    status: "completed",
    paymentStatus: "paid",
    paymentMethod: "upi",
    isReviewed: true,
  },
  // Active booking — Arjun has the Nexon EV now
  {
    bookingNumber: bookingNum(),
    user: user3._id,
    car: nexonEV._id,
    pickupLocation: delhi._id,
    dropLocation: delhi._id,
    pickupDate: d(-1),
    dropDate: d(2),
    totalDays: 3,
    pricePerDay: nexonEV.pricePerDay,
    baseAmount: nexonEV.pricePerDay * 3,
    taxAmount: Math.round(nexonEV.pricePerDay * 3 * 0.18),
    totalAmount: Math.round(nexonEV.pricePerDay * 3 * 1.18),
    securityDeposit: nexonEV.securityDeposit,
    status: "active",
    paymentStatus: "paid",
    paymentMethod: "card",
    isReviewed: false,
  },
  // Confirmed upcoming — Rahul booked BMW
  {
    bookingNumber: bookingNum(),
    user: user1._id,
    car: bmw._id,
    pickupLocation: mumbaiAirport._id,
    dropLocation: mumbaiAirport._id,
    pickupDate: d(3),
    dropDate: d(6),
    totalDays: 3,
    pricePerDay: bmw.pricePerDay,
    baseAmount: bmw.pricePerDay * 3,
    taxAmount: Math.round(bmw.pricePerDay * 3 * 0.18),
    totalAmount: Math.round(bmw.pricePerDay * 3 * 1.18),
    securityDeposit: bmw.securityDeposit,
    status: "confirmed",
    paymentStatus: "paid",
    paymentMethod: "card",
    isReviewed: false,
  },
  // Pending — Priya booked Innova
  {
    bookingNumber: bookingNum(),
    user: user2._id,
    car: innova._id,
    pickupLocation: mumbaiAirport._id,
    dropLocation: mumbaiHub._id,
    pickupDate: d(5),
    dropDate: d(7),
    totalDays: 2,
    pricePerDay: innova.pricePerDay,
    baseAmount: innova.pricePerDay * 2,
    taxAmount: Math.round(innova.pricePerDay * 2 * 0.18),
    totalAmount: Math.round(innova.pricePerDay * 2 * 1.18),
    securityDeposit: innova.securityDeposit,
    status: "pending",
    paymentStatus: "pending",
    isReviewed: false,
  },
  // Cancelled — Arjun cancelled the Thar
  {
    bookingNumber: bookingNum(),
    user: user3._id,
    car: thar._id,
    pickupLocation: delhi._id,
    dropLocation: delhi._id,
    pickupDate: d(1),
    dropDate: d(3),
    totalDays: 2,
    pricePerDay: thar.pricePerDay,
    baseAmount: thar.pricePerDay * 2,
    taxAmount: Math.round(thar.pricePerDay * 2 * 0.18),
    totalAmount: Math.round(thar.pricePerDay * 2 * 1.18),
    securityDeposit: thar.securityDeposit,
    status: "cancelled",
    paymentStatus: "refunded",
    cancellationReason: "Change of travel plans",
    cancelledBy: "user",
    cancelledAt: d(-2),
    isReviewed: false,
  },
  // Completed — Arjun booked Honda City
  {
    bookingNumber: bookingNum(),
    user: user3._id,
    car: hondaCity._id,
    pickupLocation: mumbaiHub._id,
    dropLocation: mumbaiHub._id,
    pickupDate: d(-20),
    dropDate: d(-18),
    totalDays: 2,
    pricePerDay: hondaCity.pricePerDay,
    baseAmount: hondaCity.pricePerDay * 2,
    taxAmount: Math.round(hondaCity.pricePerDay * 2 * 0.18),
    totalAmount: Math.round(hondaCity.pricePerDay * 2 * 1.18),
    securityDeposit: hondaCity.securityDeposit,
    status: "completed",
    paymentStatus: "paid",
    paymentMethod: "netbanking",
    isReviewed: true,
  },
  // Completed — Rahul booked Swift
  {
    bookingNumber: bookingNum(),
    user: user1._id,
    car: swift._id,
    pickupLocation: mumbaiHub._id,
    dropLocation: mumbaiHub._id,
    pickupDate: d(-15),
    dropDate: d(-13),
    totalDays: 2,
    pricePerDay: swift.pricePerDay,
    baseAmount: swift.pricePerDay * 2,
    taxAmount: Math.round(swift.pricePerDay * 2 * 0.18),
    totalAmount: Math.round(swift.pricePerDay * 2 * 1.18),
    securityDeposit: swift.securityDeposit,
    status: "completed",
    paymentStatus: "paid",
    paymentMethod: "upi",
    isReviewed: true,
  },
  // Completed — Priya booked Innova
  {
    bookingNumber: bookingNum(),
    user: user2._id,
    car: innova._id,
    pickupLocation: mumbaiAirport._id,
    dropLocation: mumbaiHub._id,
    pickupDate: d(-25),
    dropDate: d(-22),
    totalDays: 3,
    pricePerDay: innova.pricePerDay,
    baseAmount: innova.pricePerDay * 3,
    taxAmount: Math.round(innova.pricePerDay * 3 * 0.18),
    totalAmount: Math.round(innova.pricePerDay * 3 * 1.18),
    securityDeposit: innova.securityDeposit,
    status: "completed",
    paymentStatus: "paid",
    paymentMethod: "card",
    isReviewed: true,
  },
]);
console.log(`Created ${bookings.length} bookings`);

const [b_creta_rahul, b_city_priya, , , , , b_city_arjun, b_swift_rahul, b_innova_priya2] =
  bookings;

// ─── Reviews ──────────────────────────────────────────────────────────────────
await Review.insertMany([
  {
    user: user1._id,
    car: creta._id,
    booking: b_creta_rahul._id,
    rating: 5,
    title: "Absolutely loved it!",
    comment:
      "The Creta was in pristine condition. Pickup was smooth, and the car drove beautifully. Will definitely rent again.",
    aspects: { cleanliness: 5, comfort: 5, performance: 4, valueForMoney: 5 },
    isApproved: true,
    isVisible: true,
  },
  {
    user: user2._id,
    car: hondaCity._id,
    booking: b_city_priya._id,
    rating: 4,
    title: "Great city car",
    comment:
      "Honda City was fuel efficient and comfortable. Drop-off at airport was very convenient. Minor issue with AC initially but resolved quickly.",
    aspects: { cleanliness: 4, comfort: 4, performance: 4, valueForMoney: 4 },
    isApproved: true,
    isVisible: true,
  },
  {
    user: user3._id,
    car: hondaCity._id,
    booking: b_city_arjun._id,
    rating: 5,
    title: "Perfect for Mumbai roads",
    comment:
      "Picked up the Honda City from Mumbai Hub — car was spotless and fuel tank was full. Handled city traffic like a dream. Great value for the price.",
    aspects: { cleanliness: 5, comfort: 5, performance: 4, valueForMoney: 5 },
    isApproved: true,
    isVisible: true,
  },
  {
    user: user1._id,
    car: swift._id,
    booking: b_swift_rahul._id,
    rating: 4,
    title: "Budget-friendly and fun",
    comment:
      "The Swift was a blast to drive. Very fuel efficient and easy to park. Great pick for a quick city trip. Would recommend for solo travellers.",
    aspects: { cleanliness: 4, comfort: 4, performance: 4, valueForMoney: 5 },
    isApproved: true,
    isVisible: true,
  },
  {
    user: user2._id,
    car: innova._id,
    booking: b_innova_priya2._id,
    rating: 5,
    title: "Spacious and comfortable family ride",
    comment:
      "Rented the Innova Crysta for a family airport transfer. Seven seats with plenty of luggage space. Driver comfort is top-notch and the rear AC was a lifesaver.",
    aspects: { cleanliness: 5, comfort: 5, performance: 5, valueForMoney: 4 },
    isApproved: true,
    isVisible: true,
  },
]);
console.log("Created 5 approved reviews");

// ─── Coupons ──────────────────────────────────────────────────────────────────
await Coupon.insertMany([
  {
    code: "WELCOME20",
    description: "20% off on your first booking",
    type: "percentage",
    value: 20,
    minBookingAmount: 2000,
    maxDiscountAmount: 1500,
    startDate: d(-30),
    endDate: d(60),
    usageLimit: 100,
    perUserLimit: 1,
    isActive: true,
    createdBy: admin._id,
  },
  {
    code: "FLAT500",
    description: "Flat ₹500 off on any booking",
    type: "fixed",
    value: 500,
    minBookingAmount: 3000,
    startDate: d(-10),
    endDate: d(30),
    usageLimit: 200,
    perUserLimit: 2,
    isActive: true,
    createdBy: admin._id,
  },
  {
    code: "LUXE15",
    description: "15% off on luxury car rentals",
    type: "percentage",
    value: 15,
    minBookingAmount: 8000,
    maxDiscountAmount: 3000,
    startDate: d(-5),
    endDate: d(90),
    usageLimit: 50,
    perUserLimit: 1,
    applicableCarTypes: ["luxury"],
    isActive: true,
    createdBy: admin._id,
  },
]);
console.log("Created 3 coupons (WELCOME20, FLAT500, LUXE15)");

// ─── Update location car counts ───────────────────────────────────────────────
for (const loc of locations) {
  const count = await Car.countDocuments({ location: loc._id, isActive: true });
  await Location.findByIdAndUpdate(loc._id, { carCount: count });
}

console.log("\n✅ Seed complete!\n");
console.log("─── Login credentials ──────────────────────────");
console.log("  Admin : admin@driveease.com  / admin123");
console.log("  User 1: rahul@example.com    / password123");
console.log("  User 2: priya@example.com    / password123");
console.log("  User 3: arjun@example.com    / password123");
console.log("─── Coupons ────────────────────────────────────");
console.log("  WELCOME20 — 20% off (max ₹1500), min ₹2000");
console.log("  FLAT500   — ₹500 off, min ₹3000");
console.log("  LUXE15    — 15% off luxury, min ₹8000");
console.log("────────────────────────────────────────────────");

await mongoose.disconnect();
